; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano_33_iot]
platform = atmelsam
board = nano_33_iot
framework = arduino
lib_deps = 
    jgromes/RadioLib@^7.2.0
    https://github.com/PatrickBaus/Arduino-TMP1075
;test_filter = onboard/*


; [env:testing]
; platform = native
; src_filter =
;     +<*>
;     -<main.cpp>
;     -<fem_control.cpp>
;     -<radio_driver.cpp>
;     -<sensors.cpp>
; build_flags = -std=gnu++11
; lib_deps =
;     ArduinoFake
;     jgromes/RadioLib@^7.2.0
;     https://github.com/PatrickBaus/Arduino-TMP1075
; test_filter = native/*